# Generated by Django 3.1.2 on 2020-10-29 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpasstoken',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpasstoken',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
