# Generated by Django 3.1.2 on 2020-10-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201029_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpasstoken',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
